name = "HolidayJp"
uuid = "a0f9f270-aa2e-430a-aba3-8faa33662de6"
authors = ["Kenta Murata <mrkn@mrkn.jp> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
